[project]
name = "py-stt"
version = "0.1.0"
description = "Simple stt with llm post-processor"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ollama>=0.5.1",
    "openai-whisper>=20240930",
    "pyperclip>=1.9.0",
    "scipy>=1.15.3",
    "sounddevice>=0.5.2",
]
